require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'spec/**/*.rb'
    - 'tmp/**/*.rb'
    - 'bin/**/*.rb'
    - 'vendor/**/*' # Github actions bundles into vendor
  Include:
    - 'RakeFile'

Metrics/MethodLength:
  Max: 20

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec