require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable
  Include:
    - 'RakeFile'
    - 'lib/**/*.rb'
    - 'tasks/**/*.rb'

Metrics/MethodLength:
  Max: 20

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec